### ISSUE TITLE
Dynamic conversion fails with a correct implementation (but passed with the picked solution).

### ISSUE THREAD

**Issue by jtonic** [this-is-kotlin/exercises#3]
In the definition of the exercise is stated:

> Write a function that uses that map to convert an amount in a given currency to the requested currency. **If the currency pair is not defined, throw an exception.**`

But the suggested (picked) solution doesn't handle the throw exception case, and a provided solution correctly handling it fails in the following test - for the  "XXX" input data.

```kotlin
    @ParameterizedTest(name = "same currency should return same amount: {0}")
    @ValueSource(strings = ["EUR", "RON", "XXX", "USD", "GBP"])
    fun `same currency should return same amount`(currency: String) {
        Assertions.assertEquals(1.55, convert(fromCurrency = currency, toCurrency = currency, amount = 1.55))
    }

```

**Comment by tibtof** [comment]
Thanks for reporting this. I will update the requirement to include this behaviour: converting to the same currency should always work and return the initial amount.
