### ISSUE TITLE
Basic Gradle sync fails on 2023.2 INTELLIJ 

### ISSUE THREAD

**Issue by amIT-nitb** [this-is-kotlin/exercises#5]
I started the project but seems the basic gradle sync itself is facing, i tried to  check  kotlin vesion 1.7 as well but it didnt help 

ENVIROMENT USED 
INTELLI COMMUNITY EDITION 2023.2

Build #IC-232.8660.185, built on July 26, 2023

Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
 

Build file 'D:\IDE\{ this is Kotlin }\build.gradle' line: 44

A problem occurred evaluating root project '{_this_is_Kotlin_}'.
> Could not create task ':collections-Balance_By_Currency:compileKotlin'.
   > Cannot use @TaskAction annotation on method AbstractKotlinCompile.execute() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 751ms

**Comment by tibtof** [comment]
thanks for letting me know!

**Comment by amIT-nitb** [comment]
I was able to get to work by making changes in build.gradle  couldn't create a branch here so here are the change , feel free to incorporate them.
https://github.com/amIT-nitb/this-is-kotlin/commit/64836217fdff21b0a7939db3152e3dfd54c6935e

**Comment by tibtof** [comment]
@amIT-nitb thanks!
