### ISSUE TITLE
Cannot use @TaskAction annotation on method AbstractKotlinCompile.execute() 

### ISSUE THREAD

**Issue by javapda** [this-is-kotlin/exercises#7]
When starting this course "{ this is kotlin }" on a Windows 11 pro machine running Intellij IDEA (see details below) getting the following errors: (btw, line 44 of build.gradle is "compileKotlin.destinationDir = compileJava.destinationDir")
+-----------------------------------------------------------------------------

Build file 'C:\Users\javap\{ this is Kotlin }\build.gradle' line: 44

A problem occurred evaluating root project '{_this_is_Kotlin_}'.
> Could not create task ':collections-Balance_By_Currency:compileKotlin'.
   > Cannot use @TaskAction annotation on method AbstractKotlinCompile.execute() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 14s
The build scan was not published due to a configuration problem.
The Gradle Terms of Service have not been agreed to.
For more information, please see https://gradle.com/help/plugin-terms-of-service.
Alternatively, if you are using Gradle Enterprise, specify the server location.
For more information, please see https://gradle.com/help/plugin-enterprise-config.

+-----------------------------------------------------------------------------
Contents of build.gradle:
buildscript {
    ext.kotlin_version = '1.5.10'

    repositories {
        mavenCentral()

    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

def printOutput(def output) {
    return tasks.create("printOutput") {
        println "#educational_plugin_checker_version 1"
        def separator = System.lineSeparator()
        def lines = output.toString().split("(?<=${separator})|(?=${separator})")
        for (line in lines) {
            println "#educational_plugin" + line
        }
    }
}

subprojects {
    apply plugin: 'application'
    apply plugin: 'java'
    apply plugin: 'kotlin'

    sourceCompatibility = 1.8

    repositories {
        mavenCentral()

    }

    dependencies {
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
        testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter', version: '5.7.2'
        testImplementation 'org.jetbrains.kotlin:kotlin-test'
        testImplementation 'io.mockk:mockk:1.12.0'
    }

    compileKotlin.destinationDir = compileJava.destinationDir

    compileKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }
    compileTestKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }

    sourceSets {
        main {
            kotlin.srcDir 'src'
            java.srcDir 'src'
        }
        test {
            kotlin.srcDir 'test'
            java.srcDir 'test'
        }
    }

    mainClassName = project.hasProperty("mainClass") ? project.getProperty("mainClass") : ""
    test {
        useJUnitPlatform()
        outputs.upToDateWhen { false }
        afterTest { TestDescriptor test, TestResult result ->
            if (result.resultType == TestResult.ResultType.FAILURE) {
                def message = result.exception?.message ?: "Wrong answer"
                def lines = message.readLines()
                println "#educational_plugin FAILED + " + lines[0]
                lines.subList(1, lines.size()).forEach { line ->
                    println "#educational_plugin" + line
                }
                // we need this to separate output of different tests
                println()
            }
        }
    }

    if (project.hasProperty("educationalRun") && "true".equalsIgnoreCase(project.getProperty("educationalRun"))) {
        def runOutput = new ByteArrayOutputStream()
        tasks.run.setStandardOutput(runOutput)
        tasks.run.doLast { printOutput(runOutput) }
    }
}

project(':util') {
    dependencies {
        implementation group: 'junit', name: 'junit', version: '4.12'
    }
}

configure(subprojects.findAll { it.name != 'util' }) {
    dependencies {
        implementation project(':util').sourceSets.main.output
        testImplementation project(':util').sourceSets.test.output
    }
}

+-----------------------------------------------------------------------------
OS: Windows 11 Pro
+-----------------------------------------------------------------------------
Intellij IDEA Info
IntelliJ IDEA 2024.1.1 (Community Edition)
Build #IC-241.15989.150, built on April 29, 2024
Runtime version: 17.0.10+1-b1207.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.edu (2024.4-2024.1-742)
  com.godwin.kdocer (1.6)
Kotlin: 241.15989.150-IJ

**Comment by tibtof** [comment]
@javapda thanks for reporting and investigating this. I submitted an update to the marketplace last week, that was just approved today. Please try again with the latest version.

**Comment by javapda** [comment]
![this is kotlin course dialog updated to 24-May-2024](https://github.com/this-is-kotlin/exercises/assets/471352/0efa9a11-fc64-4589-854b-b5472b9610cc)
Hi @tibtof  - I see the course update of May 15, 2024. I restarted/re-downloaded the latest [{ this is Kotlin }](https://github.com/this-is-kotlin) course from the Marketplace in IDEA, however, I am getting the following error: 
```
Execution failed for task ':intro-Hello,_Bob:test'.
> There were failing tests. See the report at: file:///C:/Users/javap/%7B%20this%20is%20Kotlin%20%7D/intro/Hello,%20Bob/build/reports/tests/test/index.html

* Try:
> Run with --scan to get full insights.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 3s
5 actionable tasks: 5 executed
```
Not sure how to adjust the gradle behavior in response to the CHECK button to include the suggested options (--scan, --warning-mode-all)

Please, let me know if there is anything I can do to help sort things out. 

Thank you.

**Comment by javapda** [comment]
@tibtof  It looks like it may be due to a jvm version conflict:
```
Caused by: java.lang.UnsupportedClassVersionError: HelloBobTest has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

```



![test error log indicating jvm version issue 17 vs 21](https://github.com/this-is-kotlin/exercises/assets/471352/fadf93f4-803e-4a7c-ba5d-78d01c50b4bc)

I looked at the settings in Intellij IDEA and see an issue with #USE_PROJECT_JDK - so manually changed to 21
![JDK for importer showing #USE_PROJECT_JDK](https://github.com/this-is-kotlin/exercises/assets/471352/23b1b8dd-d517-4eda-955d-00717303a52e)



![JDK for importer showing 21](https://github.com/this-is-kotlin/exercises/assets/471352/a3eb6c0c-1479-4ca2-b5b8-97458b8984bc)

However, still showing the same version conflict.

So, now looking for where the project is configured to use JRE 17. Any suggestions?

**Comment by javapda** [comment]
@tibtof Ok, I think things are stable. I went into the Gradle view for the { this is Kotlin } project. Clicked the Settings icon then adjusted the Gradle JVM to set to 21 [Oracle OpenJDK 21.0.1].

![Gradle Settings for project with corrected Gradle JVM to Oracle OpenJDK 21 0 1](https://github.com/this-is-kotlin/exercises/assets/471352/8fc79aaa-6c5d-4713-93f6-92cf54e99ff5)

Thank you for looking into this @tibtof

**Comment by tibtof** [comment]
@javapda Thanks for the investigation, I should include setting up the gradle jvm in the documentation, is it ok if I reuse your screenshots for that?

**Comment by javapda** [comment]
@tibtof  By all means you can use these screenshots.
